# Generated by Django 5.1.4 on 2025-04-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HarmonicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harmonic_number', models.IntegerField(db_index=True)),
                ('v_prevail_ang1', models.FloatField(blank=True, null=True)),
                ('v_prevail_ang2', models.FloatField(blank=True, null=True)),
                ('v_prevail_ang3', models.FloatField(blank=True, null=True)),
                ('v_prevail_ang4', models.FloatField(blank=True, null=True)),
                ('v_prevail_mag1', models.FloatField(blank=True, null=True)),
                ('v_prevail_mag2', models.FloatField(blank=True, null=True)),
                ('v_prevail_mag3', models.FloatField(blank=True, null=True)),
                ('v_prevail_mag4', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
