# Generated by Django 5.1.4 on 2025-04-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ludwig', '0002_harmonicrecord_i_prevail_ang1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harm_number', models.IntegerField(db_index=True)),
                ('p_harm_total', models.FloatField()),
                ('i_prevail_mag_1', models.FloatField()),
                ('i_prevail_ang_1', models.FloatField()),
                ('v_prevail_mag_1', models.FloatField()),
                ('v_prevail_ang_1', models.FloatField()),
                ('i_prevail_mag_2', models.FloatField()),
                ('i_prevail_ang_2', models.FloatField()),
                ('v_prevail_mag_2', models.FloatField()),
                ('v_prevail_ang_2', models.FloatField()),
                ('i_prevail_mag_3', models.FloatField()),
                ('i_prevail_ang_3', models.FloatField()),
                ('v_prevail_mag_3', models.FloatField()),
                ('v_prevail_ang_3', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='HarmonicRecord',
        ),
    ]
